Remove no longer relevant function definitions from netlink/handle_unspecified
	# github.com/vishvananda/netlink
	vendor/src/github.com/vishvananda/netlink/handle_unspecified.go:184: undefined: Filter
	vendor/src/github.com/vishvananda/netlink/handle_unspecified.go:188: undefined: Filter
	vendor/src/github.com/vishvananda/netlink/handle_unspecified.go:192: undefined: Filter
f