Avoid building libnetwork/netutils/test_utils on non-Linux, since it uses Linux syscalls
It also relies on /proc being present, which obviously is only going to be floating around on Linux

	# github.com/docker/libnetwork/netutils
	vendor/src/github.com/docker/libnetwork/netutils/test_utils.go:26: undefined: syscall.Unshare
	vendor/src/github.com/docker/libnetwork/netutils/test_utils.go:26: undefined: syscall.CLONE_NEWNET
f